### ISSUE TITLE
[TESTBUG][upstream]-Xcomp选项test/jdk/com/sun/jndi/dns/ConfigTests/PortUnreachable.java随机失败

### ISSUE THREAD

**Issue by sendaoYan** [alibaba/dragonwell17#169]
默认选项运行50次全部PASS：
```bash
expoert test=test/jdk/com/sun/jndi/dns/ConfigTests/PortUnreachable.java
function runJtreg() { jtreg -ea -esa -timeoutFactor:4 -v:fail,error,time,nopass -nr -w $dir/index-$1 $test &> $dir/$1.log ; if [[ 0 -ne $? ]] ; then echo -n "$1 " ; else rm -rf $dir/index-$1 $dir/$1.log ; fi ; } ; export -f runJtreg ; export dir="tmp-jtreg-"`basename ${test##* } .java` ; rm -rf $dir ; mkdir -p $dir ; time seq 50 | xargs -i -n 1 -P `nproc` bash -c "runJtreg {}" ; echo total fail number: `ls $dir/*.log 2> /dev/null | wc | awk '{print $1}'`
```

![image](https://github.com/dragonwell-project/dragonwell17/assets/24123821/340b0b78-2a41-4027-8d98-c063da3c4d87)

-Xcomp运行50次全部fail：

```bash
expoert test=test/jdk/com/sun/jndi/dns/ConfigTests/PortUnreachable.java
function runJtreg() { jtreg -Xcomp -ea -esa -timeoutFactor:4 -v:fail,error,time,nopass -nr -w $dir/index-$1 $test &> $dir/$1.log ; if [[ 0 -ne $? ]] ; then echo -n "$1 " ; else rm -rf $dir/index-$1 $dir/$1.log ; fi ; } ; export -f runJtreg ; export dir="tmp-jtreg-"`basename ${test##* } .java` ; rm -rf $dir ; mkdir -p $dir ; time seq 50 | xargs -i -n 1 -P `nproc` bash -c "runJtreg {}" ; echo total fail number: `ls $dir/*.log 2> /dev/null | wc | awk '{print $1}'`
```

```log
STDERR:
java.lang.RuntimeException: Failed: call took 3573 ms, expected less than 3000 ms
	at PortUnreachable.handleException(PortUnreachable.java:101)
	at TestBase.launch(TestBase.java:84)
	at TestBase.run(TestBase.java:50)
	at PortUnreachable.main(PortUnreachable.java:60)
```

![image](https://github.com/dragonwell-project/dragonwell17/assets/24123821/964ca896-efee-4b17-a26f-48a0dc4b5627)
[1.log](https://github.com/dragonwell-project/dragonwell17/files/13246484/1.log)

**Comment by sendaoYan** [comment]
https://code.alibaba-inc.com/os-quality/tone-matrix/codereview/14536536
