### ISSUE TITLE
[upstream]-Xcomp选项运行tools/javac/completionDeps/DepsAndAnno.java用例超时

### ISSUE THREAD

**Issue by sendaoYan** [alibaba/dragonwell17#171]
https://tone.aliyun-inc.com/ws/xesljfzh/test_result/239361
【环境准备】
```
wget -O jtreg.zip https://compiler-ci-bucket.oss-cn-hangzhou.aliyuncs.com/jdk/tools/jtreg-6.1.1.zip
wget -O binary.tar.gz https://dragonwell.oss-cn-shanghai.aliyuncs.com/test-58/OpenJDK17U-jdk_x64_linux_dragonwell_2023-10-23-02-59.tar.gz
wget https://dragonwell.oss-cn-shanghai.aliyuncs.com/test-58/OpenJDK17U-testimage_x64_linux_dragonwell_2023-10-23-02-59.tar.gz -O test-image.tar.gz
git clone https://github.com/dragonwell-project/dragonwell17.git -b wip_dragonwell_standard_merge_branch jdk-repo

mkdir binary-download 
tar xzvf binary.tar.gz -C binary-download ; cd binary-download && export JAVA_HOME=$PWD ; export PATH=$JAVA_HOME/bin:$PATH ; export TEST_JDK_HOME=$JAVA_HOME &&cd -
make test-image ; tar xzvf test-image.tar.gz -C test-image
unzip jtreg.zip; cd jtreg ; export JT_HOME=$PWD ; export PATH=$PWD/bin:$PATH ; cd -

test=\
jdk-repo/test/langtools/tools/javac/completionDeps/DepsAndAnno.java
args='-Xcomp'
native='-nativepath:./test-image/hotspot/jtreg/native'
jtreg -w tmp -nr -v:fail,error $native  $args $test
```

【对比测试】
jdk-repo/test/langtools/tools/javac/completionDeps/DepsAndAnno.java
jdk-repo/test/langtools/tools/javac/launcher/SourceLauncherTest.java

dragonwell17 release版本同样错误.
wget https://dragonwell.oss-cn-shanghai.aliyuncs.com/17.0.8.0.8%2B7/Alibaba_Dragonwell_Standard_17.0.8.0.8.7_x64_linux.tar.gz
 
```
[root@VM20210305-10 d17-release]# java -version; java -Xinternalversion
openjdk version "17.0.8" 2023-07-18
OpenJDK Runtime Environment (Alibaba Dragonwell Standard Edition)-17.0.8.0.8+7-GA (build 17.0.8+7)
OpenJDK 64-Bit Server VM (Alibaba Dragonwell Standard Edition)-17.0.8.0.8+7-GA (build 17.0.8+7, mixed mode, sharing)
OpenJDK 64-Bit Server VM (17.0.8+7) for linux-aarch64 JRE (17.0.8+7), built on Jul 18 2023 00:00:00 by "dragonwell" with gcc 10.3.0

```

temurin17 同样错误.
https://github.com/adoptium/temurin17-binaries/releases/download/jdk-17.0.9%2B9/OpenJDK17U-jdk_x64_linux_hotspot_17.0.9_9.tar.gz
```
[root@VM20190228-137 t17]# java -version; java -Xinternalversion
openjdk version "17.0.9" 2023-10-17
OpenJDK Runtime Environment Temurin-17.0.9+9 (build 17.0.9+9)
OpenJDK 64-Bit Server VM Temurin-17.0.9+9 (build 17.0.9+9, mixed mode, sharing)
OpenJDK 64-Bit Server VM (17.0.9+9) for linux-amd64 JRE (17.0.9+9), built on Oct 17 2023 00:00:00 by "admin" with gcc 10.3.0


```

【用例日志】

```

"MainThread" #32 prio=5 os_prio=0 cpu=249.89ms elapsed=4.76s tid=0x00007fc3ac3daa00 nid=0x9f60e waiting on condition  [0x00007fc2ea17c000]
   java.lang.Thread.State: RUNNABLE
        at java.nio.file.Files.newByteChannel(java.base@17.0.8/Files.java:426)
        at java.nio.file.spi.FileSystemProvider.newInputStream(java.base@17.0.8/FileSystemProvider.java:422)
        at java.nio.file.Files.newInputStream(java.base@17.0.8/Files.java:160)
        at com.sun.tools.javac.file.PathFileObject.openInputStream(jdk.compiler@17.0.8/PathFileObject.java:461)
        at com.sun.tools.javac.file.PathFileObject.getCharContent(jdk.compiler@17.0.8/PathFileObject.java:482)
        at com.sun.tools.javac.main.JavaCompiler.readSource(jdk.compiler@17.0.8/JavaCompiler.java:594)
        at com.sun.tools.javac.main.JavaCompiler.parse(jdk.compiler@17.0.8/JavaCompiler.java:657)
        at com.sun.tools.javac.main.JavaCompiler.parseFiles(jdk.compiler@17.0.8/JavaCompiler.java:1006)
        at com.sun.tools.javac.main.JavaCompiler.parseFiles(jdk.compiler@17.0.8/JavaCompiler.java:993)
        at com.sun.tools.javac.main.JavaCompiler.compile(jdk.compiler@17.0.8/JavaCompiler.java:919)
        at com.sun.tools.javac.main.Main.compile(jdk.compiler@17.0.8/Main.java:317)
        at com.sun.tools.javac.main.Main.compile(jdk.compiler@17.0.8/Main.java:176)
        at com.sun.tools.javac.Main.compile(jdk.compiler@17.0.8/Main.java:82)
        at toolbox.JavacTask.runCommand(JavacTask.java:394)
        at toolbox.JavacTask.run(JavacTask.java:328)
        at DepsAndAnno.main(DepsAndAnno.java:53)
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(java.base@17.0.8/Native Method)
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(java.base@17.0.8/NativeMethodAccessorImpl.java:77)
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(java.base@17.0.8/DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(java.base@17.0.8/Method.java:568)
        at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
        at java.lang.Thread.run(java.base@17.0.8/Thread.java:833)
```

【版本信息】
```
[root@VM20190228-137 d17]# uname -a ; cat /etc/os-release ; free -h; lscpu| head -n 25;java -version; java -Xinternalversion
Linux VM20190228-137 5.10.134-14.al8.x86_64 #1 SMP Thu Apr 27 16:46:29 CST 2023 x86_64 x86_64 x86_64 GNU/Linux
NAME="Alibaba Cloud Linux"
VERSION="3 (Soaring Falcon)"
ID="alinux"
ID_LIKE="rhel fedora centos anolis"
VERSION_ID="3"
PLATFORM_ID="platform:al8"
PRETTY_NAME="Alibaba Cloud Linux 3 (Soaring Falcon)"
ANSI_COLOR="0;31"
HOME_URL="https://www.aliyun.com/"

              total        used        free      shared  buff/cache   available
Mem:           15Gi       588Mi       2.4Gi       754Mi        12Gi        13Gi
Swap:            0B          0B          0B
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              4
On-line CPU(s) list: 0-3
Thread(s) per core:  2
Core(s) per socket:  1
Socket(s):           2
NUMA node(s):        1
Vendor ID:           GenuineIntel
BIOS Vendor ID:      Alibaba Cloud
CPU family:          6
Model:               85
Model name:          Intel(R) Xeon(R) Platinum 8163 CPU @ 2.50GHz
BIOS Model name:     pc-i440fx-2.1
Stepping:            4
CPU MHz:             2500.012
BogoMIPS:            5000.02
Hypervisor vendor:   KVM
Virtualization type: full
L1d cache:           32K
L1i cache:           32K
L2 cache:            1024K
L3 cache:            33792K
NUMA node0 CPU(s):   0-3
openjdk version "17.0.9" 2023-10-17
OpenJDK Runtime Environment (Alibaba Dragonwell Standard Edition)-17.0.8.0.9+7-GA (build 17.0.9+7)
OpenJDK 64-Bit Server VM (Alibaba Dragonwell Standard Edition)-17.0.8.0.9+7-GA (build 17.0.9+7, mixed mode, sharing)
OpenJDK 64-Bit Server VM (17.0.9+7) for linux-amd64 JRE (17.0.9+7), built on Oct 17 2023 00:00:00 by "dragonwell" with gcc 7.5.0
```

**Comment by sendaoYan** [comment]
上游最新主干分支也是超时，-Xcomp需要30s才能跑完

![image](https://github.com/dragonwell-project/dragonwell17/assets/24123821/16022a85-9782-4c9c-8616-5e91d1fd5f98)


[DepsAndAnno-Xcomp.jtr.txt](https://github.com/dragonwell-project/dragonwell17/files/13247595/DepsAndAnno-Xcomp.jtr.txt)
[DepsAndAnno-Xmixed.jtr.txt](https://github.com/dragonwell-project/dragonwell17/files/13247597/DepsAndAnno-Xmixed.jtr.txt)

**Comment by sendaoYan** [comment]
tools/javac/launcher/SourceLauncherTest.java类似

**Comment by sendaoYan** [comment]
https://code.alibaba-inc.com/os-quality/tone-matrix/codereview/14540303

**Comment by sendaoYan** [comment]
jdk/jfr/startupargs/TestStartDuration.java 类似


![image](https://github.com/dragonwell-project/dragonwell17/assets/24123821/821bed82-b073-47e5-b235-584df6265875)

[TestStartDuration-Xcomp.jtr.txt](https://github.com/dragonwell-project/dragonwell17/files/13247684/TestStartDuration-Xcomp.jtr.txt)
[TestStartDuration-Xmixed.jtr.txt](https://github.com/dragonwell-project/dragonwell17/files/13247687/TestStartDuration-Xmixed.jtr.txt)

**Comment by sendaoYan** [comment]
test/langtools/tools/javac/Paths/ClassPath.java 类似

![image](https://github.com/dragonwell-project/dragonwell17/assets/24123821/b4d1f379-1f87-47ef-bf1f-a0730aeb21e8)

[ClassPath.jtr-Xcomp.txt](https://github.com/dragonwell-project/dragonwell17/files/13247719/ClassPath.jtr-Xcomp.txt)
[ClassPath.jtr-Xmixed.txt](https://github.com/dragonwell-project/dragonwell17/files/13247720/ClassPath.jtr-Xmixed.txt)

**Comment by sendaoYan** [comment]
[tools/jar/compat/CLICompatibility.java ](https://github.com/dragonwell-releng/dragonwell-adoptium/issues/259)类似


![image](https://github.com/dragonwell-project/dragonwell17/assets/24123821/23770d57-2234-4049-8674-f4aa004c3dd2)



[CLICompatibility.jtr-Xcomp.txt](https://github.com/dragonwell-project/dragonwell17/files/13247938/CLICompatibility.jtr-Xcomp.txt)
[CLICompatibility.jtr-Xmixed.txt](https://github.com/dragonwell-project/dragonwell17/files/13247939/CLICompatibility.jtr-Xmixed.txt)

**Comment by sendaoYan** [comment]
[sun/security/validator/certreplace.sh](https://github.com/dragonwell-releng/dragonwell-adoptium/issues/258) 类似

![image](https://github.com/dragonwell-project/dragonwell17/assets/24123821/3a0837a3-8d66-4e9b-8bd2-10fbdd2f52fc)


[certreplace.jtr-Xcomp.txt](https://github.com/dragonwell-project/dragonwell17/files/13247870/certreplace.jtr-Xcomp.txt)
[certreplace.jtr-Xmixed.txt](https://github.com/dragonwell-project/dragonwell17/files/13247871/certreplace.jtr-Xmixed.txt)

**Comment by sendaoYan** [comment]
[javax/net/ssl/Stapling/HttpsUrlConnClient.java](https://github.com/dragonwell-releng/dragonwell-adoptium/issues/257) 类似

![image](https://github.com/dragonwell-project/dragonwell17/assets/24123821/fe5d4a99-d51e-400a-83cb-ecb52195abb3)

[HttpsUrlConnClient.jtr-Xcomp.txt](https://github.com/dragonwell-project/dragonwell17/files/13247888/HttpsUrlConnClient.jtr-Xcomp.txt)
[HttpsUrlConnClient.jtr-Xmixed.txt](https://github.com/dragonwell-project/dragonwell17/files/13247889/HttpsUrlConnClient.jtr-Xmixed.txt)

**Comment by sendaoYan** [comment]
[java/security/Security/ClassLoaderDeadlock/ClassLoaderDeadlock.sh](https://github.com/dragonwell-releng/dragonwell-adoptium/issues/256) 类似

![image](https://github.com/dragonwell-project/dragonwell17/assets/24123821/ed43f80a-4f2a-42c6-9eb3-7ff414a90e0e)

[ClassLoaderDeadlock.jtr-Xcomp.txt](https://github.com/dragonwell-project/dragonwell17/files/13248012/ClassLoaderDeadlock.jtr-Xcomp.txt)
[ClassLoaderDeadlock.jtr-Xmixed.txt](https://github.com/dragonwell-project/dragonwell17/files/13248013/ClassLoaderDeadlock.jtr-Xmixed.txt)

**Comment by sendaoYan** [comment]
j[dk/jfr/event/gc/stacktrace/TestMetaspaceParallelGCAllocationPendingStackTrace.java](https://github.com/dragonwell-releng/dragonwell-adoptium/issues/265)
jdk/jfr/event/gc/stacktrace/TestMetaspaceSerialGCAllocationPendingStackTrace.java 类似

**Comment by sendaoYan** [comment]
https://bugs.openjdk.org/browse/JDK-8340969

**Comment by sendaoYan** [comment]
https://github.com/openjdk/jdk17u-dev/pull/3102
