### ISSUE TITLE
rpm包运行用例containers/docker/TestCPUAwareness.java报错Error loading java.security file

### ISSUE THREAD

**Issue by sendaoYan** [alibaba/dragonwell17#178]
job: https://tone.aliyun-inc.com/ws/xesljfzh/test_result/248397?tab=1

测试命令：
```bash
jtreg -va -nr -w tmp jdk-repo/test/hotspot/jtreg/containers/docker/TestCPUAwareness.java
```

结果：
```
Exception in thread "main" java.lang.InternalError: Error loading java.security file
	at java.base/java.security.Security.initialize(Security.java:106)
	at java.base/java.security.Security$1.run(Security.java:84)
	at java.base/java.security.Security$1.run(Security.java:82)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
	at java.base/java.security.Security.<clinit>(Security.java:82)
	at java.base/sun.security.util.SecurityProperties.getOverridableProperty(SecurityProperties.java:57)
	at java.base/sun.security.util.SecurityProperties.privilegedGetOverridable(SecurityProperties.java:48)
	at java.base/sun.security.util.SecurityProperties.includedInExceptions(SecurityProperties.java:72)
	at java.base/sun.security.util.SecurityProperties.<clinit>(SecurityProperties.java:36)
	at java.base/sun.security.util.FilePermCompat.<clinit>(FilePermCompat.java:45)
	at java.base/java.io.FilePermission.init(FilePermission.java:319)
	at java.base/java.io.FilePermission.<init>(FilePermission.java:490)
	at java.management/java.lang.management.ManagementFactory$PlatformMBeanFinder.<clinit>(ManagementFactory.java:923)
	at java.management/java.lang.management.ManagementFactory.getPlatformMXBean(ManagementFactory.java:685)
	at java.management/java.lang.management.ManagementFactory.getOperatingSystemMXBean(ManagementFactory.java:389)
	at CheckOperatingSystemMXBean.main(CheckOperatingSystemMXBean.java:42)
```

使用dragonwell17 tar包正常：https://dragonwell.oss-cn-shanghai.aliyuncs.com/17.0.9.0.10%2B9/Alibaba_Dragonwell_Standard_17.0.9.0.10%2B9_x64_linux.tar.gz

![image](https://github.com/dragonwell-project/dragonwell17/assets/24123821/6f30c6dd-b086-4740-93e9-a6438e373e55)

相关用例：
```
containers/docker/TestCPUAwareness.java
containers/docker/TestJFREvents.java
containers/docker/TestJFRNetworkEvents.java
containers/docker/TestJcmdWithSideCar.java
containers/docker/TestMemoryAwareness.java
containers/docker/TestMemoryWithCgroupV1.java
jdk/internal/platform/docker/TestGetFreeSwapSpaceSize.java
java/security/Security/ConfigFileTest.java
tools/jlink/JLinkReproducible3Test.java
tools/jpackage/share/jdk/jpackage/tests/MainClassTest.java
```

**Comment by sendaoYan** [comment]
containers/docker/TestCPUAwareness.java
containers/docker/TestJFREvents.java
containers/docker/TestJFRNetworkEvents.java
containers/docker/TestJFRWithJMX.java
containers/docker/TestJcmdWithSideCar.java
containers/docker/TestMemoryAwareness.java
containers/docker/TestMemoryWithCgroupV1.java
以上用例重跑没有问题，issue先关闭
