### ISSUE TITLE
[upstream][TESTBUG]serviceability/dcmd/vm/TrimLibcHeapTest.java报错

### ISSUE THREAD

**Issue by sendaoYan** [alibaba/dragonwell17#186]
https://tone.aliyun-inc.com/ws/xesljfzh/test_result/255479

【环境准备】
```
wget -O jtreg.zip http://114.55.64.175:8666/compiler-ci-bucket/tools/jtreg-6.1.1.zip
wget http://114.55.64.175:8666/compiler-ci-bucket/dragonwell17/20231114-002504-781-%23153-linux.aarch64.release.standard-effce46066d79b05140bee59cff5a8591bf9f1fe.test-image.tar.gz
wget http://114.55.64.175:8666/compiler-ci-bucket/dragonwell17/20231114-002504-781-%23153-linux.aarch64.release.standard-effce46066d79b05140bee59cff5a8591bf9f1fe.jdk.tar.gz

git clone https://github.com/dragonwell-project/dragonwell17.git -b wip_dragonwell_standard_merge_branch jdk-repo

mkdir binary-download 
tar xzvf binary.tar.gz -C binary-download ; cd binary-download && export JAVA_HOME=$PWD ; export PATH=$JAVA_HOME/bin:$PATH ; export TEST_JDK_HOME=$JAVA_HOME &&cd -
make test-image; tar xzvf test-image.tar.gz -C test-image
unzip jtreg.zip; cd jtreg ; export JT_HOME=$PWD ; export PATH=$PWD/bin:$PATH ; cd -

test=\
jdk-repo/test/hotspot/jtreg/serviceability/dcmd/vm/TrimLibcHeapTest.java
args='-Xcomp'
native='-nativepath:./test-image/hotspot/jtreg/native'
jtreg  -nr -v:fail,error -w tmp  $args $native $test

```

【对比测试】

dragonwell17 release版本同样错误.
wget http://114.55.64.175:8666/compiler-ci-bucket/openjdk/jdk-17.0.9-ga/OpenJDK17U-jdk_aarch64_linux_hotspot_17.0.9_9.tar.gz

```
[root@VM20210305-10 bin]# ./java -version; ./java -Xinternalversion
openjdk version "17.0.9" 2023-10-17
OpenJDK Runtime Environment (Alibaba Dragonwell Standard Edition)-17.0.9.0.10+9-GA (build 17.0.9+9)
OpenJDK 64-Bit Server VM (Alibaba Dragonwell Standard Edition)-17.0.9.0.10+9-GA (build 17.0.9+9, mixed mode, sharing)
OpenJDK 64-Bit Server VM (17.0.9+9) for linux-aarch64 JRE (17.0.9+9), built on Oct 17 2023 00:00:00 by "dragonwell" with gcc 10.3.0
```

temurin17 同样错误.
https://github.com/adoptium/temurin17-binaries/releases/download/jdk-17.0.9%2B9/OpenJDK17U-jdk_aarch64_linux_hotspot_17.0.9_9.tar.gz

```
[root@VM20210305-10 bin]# ./java -version; ./java -Xinternalversion
openjdk version "17.0.9" 2023-10-17
OpenJDK Runtime Environment Temurin-17.0.9+9 (build 17.0.9+9)
OpenJDK 64-Bit Server VM Temurin-17.0.9+9 (build 17.0.9+9, mixed mode, sharing)
OpenJDK 64-Bit Server VM (17.0.9+9) for linux-aarch64 JRE (17.0.9+9), built on Oct 17 2023 00:00:00 by "admin" with gcc 10.3.0

```

【用例日志】

```
STDOUT:
Running DCMD 'System.trim_native_heap' through 'JMXExecutor'
---------------- stdout ----------------
Trim native heap: RSS+Swap: 64180K->64240K (+61440B)

---------------- stderr ----------------

----------------------------------------

test TrimLibcHeapTest.jmx(): failure
java.lang.RuntimeException: 'Trim native heap: RSS\+Swap: \d+[BKMG]->\d+[BKMG] \(-\d+[BKMG]\)' missing from stdout/stderr

        at jdk.test.lib.process.OutputAnalyzer.shouldMatch(OutputAnalyzer.java:340)
        at TrimLibcHeapTest.run(TrimLibcHeapTest.java:49)
        at TrimLibcHeapTest.jmx(TrimLibcHeapTest.java:55)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
        at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
        at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
        at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
        at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
        at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
        at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
        at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
        at org.testng.TestRunner.privateRun(TestRunner.java:764)
        at org.testng.TestRunner.run(TestRunner.java:585)
        at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
        at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
        at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
        at org.testng.SuiteRunner.run(SuiteRunner.java:286)
        at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
        at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
        at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
        at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
        at org.testng.TestNG.runSuites(TestNG.java:1069)
        at org.testng.TestNG.run(TestNG.java:1037)
        at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:94)
        at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:54)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
        at java.base/java.lang.Thread.run(Thread.java:840)

===============================================
serviceability/dcmd/vm/TrimLibcHeapTest.java
Total tests run: 1, Passes: 0, Failures: 1, Skips: 0
===============================================

STDERR:
 stdout: [Trim native heap: RSS+Swap: 64180K->64240K (+61440B)
];
 stderr: []
 exitValue = -1

 stdout: [Trim native heap: RSS+Swap: 64180K->64240K (+61440B)
];
 stderr: []
 exitValue = -1

java.lang.Exception: failures: 1
        at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:96)
        at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:54)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
        at java.base/java.lang.Thread.run(Thread.java:840)

JavaTest Message: Test threw exception: java.lang.Exception: failures: 1
JavaTest Message: shutting down test

STATUS:Failed.`main' threw exception: java.lang.Exception: failures: 1

```

【版本信息】
```
[root@VM20210305-10 d17]# uname -a ; cat /etc/os-release ; free -h; lscpu| head -n 25;java -version; java -Xinternalversion
Linux VM20210305-10 4.19.91-26.an8.aarch64 #1 SMP Tue May 24 13:14:10 CST 2022 aarch64 aarch64 aarch64 GNU/Linux
NAME="Anolis OS"
VERSION="8.6"
ID="anolis"
ID_LIKE="rhel fedora centos"
VERSION_ID="8.6"
PLATFORM_ID="platform:an8"
PRETTY_NAME="Anolis OS 8.6"
ANSI_COLOR="0;31"
HOME_URL="https://openanolis.cn/"

              total        used        free      shared  buff/cache   available
Mem:           15Gi       470Mi       258Mi       0.0Ki        14Gi        14Gi
Swap:            0B          0B          0B
Architecture:        aarch64
Byte Order:          Little Endian
CPU(s):              4
On-line CPU(s) list: 0-3
Thread(s) per core:  1
Core(s) per cluster: 4
Socket(s):           2
Cluster(s):          1
NUMA node(s):        1
Vendor ID:           HiSilicon
BIOS Vendor ID:      Alibaba Cloud
Model:               0
Model name:          Kunpeng-920
BIOS Model name:     virt-rhel7.6.0
Stepping:            0x1
BogoMIPS:            200.00
NUMA node0 CPU(s):   0-3
Flags:               fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm jscvt fcma dcpop asimddp asimdfhm
openjdk version "17.0.9" 2023-10-17
OpenJDK Runtime Environment (Alibaba Dragonwell Standard Edition)-17.0.7.0.7+7-GA (build 17.0.9+7)
OpenJDK 64-Bit Server VM (Alibaba Dragonwell Standard Edition)-17.0.7.0.7+7-GA (build 17.0.9+7, mixed mode, sharing)
OpenJDK 64-Bit Server VM (17.0.9+7) for linux-aarch64 JRE (17.0.9+7), built on Oct 17 2023 00:00:00 by "dragonwell" with gcc 7.5.0

```

jdk17u-dev已经修复

![image](https://github.com/dragonwell-releng/dragonwell-adoptium/assets/24123821/6d981ca8-d856-4ba7-a916-cc4fde5f2b00)

jdk17u已经修复

![image](https://github.com/dragonwell-releng/dragonwell-adoptium/assets/24123821/ce9e2599-ce87-4294-a590-89a87c138aee)

**Comment by sendaoYan** [comment]
https://code.alibaba-inc.com/os-quality/tone-matrix/codereview/14950100

**Comment by dzchun** [comment]
最新版本已修复
```
+ j -Xcomp -nativepath:images-d17/dragonwell-17.0.11.0.12+9-GA-test-image/hotspot/jtreg/native/  jdk-repo-dragonwell17/test/hotspot/jtreg/serviceability/dcmd/vm/TrimLibcHeapTest.java
~/working/dragnwell17/bin-d17/dragonwell-17.0.11.0.12+9-GA/bin/java
Directory "tmp" not found: creating
--------------------------------------------------
TEST: serviceability/dcmd/vm/TrimLibcHeapTest.java
TEST RESULT: Passed. Execution successful
--------------------------------------------------
Test results: passed: 1
Results written to /home/dongzhichun/working/dragnwell17/tmp

real    0m53.910s
user    0m58.241s
sys     0m2.290s

+ java -version;java -Xinternalversion
openjdk version "17.0.12" 2024-07-16
OpenJDK Runtime Environment (Alibaba Dragonwell Standard Edition)-17.0.11.0.12+9-GA (build 17.0.12+9)
OpenJDK 64-Bit Server VM (Alibaba Dragonwell Standard Edition)-17.0.11.0.12+9-GA (build 17.0.12+9, mixed mode, sharing)
OpenJDK 64-Bit Server VM (17.0.12+9) for linux-aarch64 JRE (17.0.12+9), built on Jul 16 2024 00:00:00 by "dragonwell" with gcc 10.3.0

```
