### ISSUE TITLE
[upstream]java/lang/reflect/callerCache/ReflectionCallerCacheTest.java run fail with -Xcomp: Class AccessTest$PublicStaticFinalField not unloaded!

### ISSUE THREAD

**Issue by sendaoYan** [alibaba/dragonwell17#196]
test command:

```shell
jtreg -va -nr -w tmp -Xcomp test/jdk/java/lang/reflect/callerCache/ReflectionCallerCacheTest.java
```

result:
```
test ReflectionCallerCacheTest.load("AccessTest$PrivateFinalField"): failure
java.lang.RuntimeException: Class AccessTest$PrivateFinalField not unloaded!
        at ReflectionCallerCacheTest.load(ReflectionCallerCacheTest.java:111)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
        at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
        at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
        at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
        at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
        at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
        at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
        at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
        at org.testng.TestRunner.privateRun(TestRunner.java:764)
        at org.testng.TestRunner.run(TestRunner.java:585)
        at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
        at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
        at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
        at org.testng.SuiteRunner.run(SuiteRunner.java:286)
        at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
        at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
        at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
        at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
        at org.testng.TestNG.runSuites(TestNG.java:1069)
        at org.testng.TestNG.run(TestNG.java:1037)
        at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:102)
        at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:58)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at com.sun.javatest.regtest.agent.MainWrapper$MainTask.run(MainWrapper.java:138)
        at java.base/java.lang.Thread.run(Thread.java:840)
```

git repo info:
```
> git remote -v ; git branch ; git log -n 1
origin  git@github.com:openjdk/jdk17u.git (fetch)
origin  git@github.com:openjdk/jdk17u.git (push)
* master
commit ca760c86642aa2e0d9b571aaabac054c0239fbdc (HEAD -> master, tag: jdk-17.0.10-ga, tag: jdk-17.0.10+7, origin/master, origin/HEAD)
Author: Christoph Langer <christoph.langer@sap.com>
Date:   Tue Jan 9 22:18:15 2024 +0100

    8323422: [17u] Remove designator DEFAULT_PROMOTED_VERSION_PRE=ea for release 17.0.10
    
    Reviewed-by: goetz
```

**Comment by sendaoYan** [comment]
https://bugs.openjdk.org/browse/JDK-8324978
