### ISSUE TITLE
[anolis]MissingResourceCauseTestRun.java报错

### ISSUE THREAD

**Issue by sendaoYan** [alibaba/dragonwell17#202]
代码仓：git@gitee.com:yansendao/java-17-alibaba-dragonwell.git a23分支

测试命令：
```shell
yum-builddep -y *.spec
\rm -rf rpmbuild
mkdir -p rpmbuild/{BUILD,RPMS,SOURCES,SPECS,SRPMS,BUILDROOT}
ls | grep -v ".log" | grep -v ".spec" | grep -v rpmbuild | xargs -i \cp -rf {} rpmbuild/SOURCES/
time rpmbuild -ba --define "_topdir $PWD/rpmbuild"  *.spec &> build.log
```

结果：
```
STDERR:
java.lang.RuntimeException: Execution of the test failed. Unexpected exit code: 1
	at MissingResourceCauseTestRun.runCmd(MissingResourceCauseTestRun.java:97)
	at MissingResourceCauseTestRun.main(MissingResourceCauseTestRun.java:60)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:312)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

[build.log.zip](https://github.com/user-attachments/files/15823194/build.log.zip)

**Comment by sendaoYan** [comment]
单跑复现命令：
```
rm -rf tmp ; jtreg -jdk:/root/java-17-alibaba-dragonwell-ysd-a23/rpmbuild/BUILD/dragonwell17-dragonwell-standard-17.0.8.0.8-7_jdk-17.0.8-ga/bootbuild/jdk17.build-main/images/jdk -v:fail,error -nr -w tmp rpmbuild/BUILD/dragonwell17-dragonwell-standard-17.0.9.0.10-9_jdk-17.0.9-ga/dragonwell/test/jdk/java/util/ResourceBundle/Control/MissingResourceCauseTestRun.java
```


https://dragonwell.oss-cn-shanghai.aliyuncs.com/17.0.9.0.10%2B9/Alibaba_Dragonwell_Standard_17.0.9.0.10%2B9_x64_linux.tar.gz 使用该二进制也报了同样的错误

**Comment by sendaoYan** [comment]
https://github.com/openjdk/jdk/pull/19732
