### ISSUE TITLE
[dragonwell17][nightly]jdk/jfr/event/gc/stacktrace/TestParallelMarkSweepAllocationPendingStackTrace.java随机报错java.lang.OutOfMemoryError: GC overhead limit exceeded

### ISSUE THREAD

**Issue by sendaoYan** [alibaba/dragonwell17#211]
https://tone.aliyun-inc.com/ws/xesljfzh/test_result/420999?tab=1   
【环境准备】

```
BINARY_URL=oss://compiler-ci-bucket/dragonwell17/20241112-002511-929-#533-linux.x86_64.release.standard-d6dc7d4bcb2e2664cc68dbc0960ce76bb2aef63a.jdk.tar.gz
TEST_IMAGE=oss://compiler-ci-bucket/dragonwell17/20241112-002511-929-#533-linux.x86_64.release.standard-d6dc7d4bcb2e2664cc68dbc0960ce76bb2aef63a.test-image.tar.gz
JTREG_URL=oss://compiler-ci-bucket/jdk/tools/jtreg-7.3.1.1.zip
JDK_REPO=git@github.com:dragonwell-project/dragonwell17.git
JDK_BRANCH=standard
cd ~/tone/tone-matrix-compiler/common;./ossutil.bin_$(arch) -i;cd -
alias oss="~/tone/tone-matrix-compiler/common/ossutil.bin_$(arch) -e oss-cn-hangzhou.aliyuncs.com -u jvm_dev-b  ~/tone/tone-matrix-compiler/common/ossutil_bin/ossutil -o download -f -r"

部署二进制：
oss $BINARY_URL -l ${BINARY_URL##*/}
mkdir bin-dragonwell17;tar -xf ${BINARY_URL##*/} -C bin-dragonwell17
oss $TEST_IMAGE-l ${TEST_IMAGE##*/}
mkdir images-dragonwell17;tar -xf ${BINARY_URL##*/} -C images-dragonwell17

部署jtreg工具：
oss $JTREG_URL -l ${JTREG_URL##*/};unzip ${JTREG_URL##*/}

部署用例repo
git clone -b $JDK_BRANCH $JDK_REPO jdk-repo

执行以下命令：
cd bin-dragonwell17 && export JAVA_HOME=$PWD ; export PATH=$JAVA_HOME/bin:$PATH ; export TEST_JDK_HOME=$JAVA_HOME && cd -
cd jtreg ;export JT_HOME=$PWD ; export PATH=$PWD/bin:$PATH;cd -

jtreg  -nr -v:fail,error -w tmp  -Xmixed   jdk-repo/test/jdk/jdk/jfr/event/gc/stacktrace/TestParallelMarkSweepAllocationPendingStackTrace.java
```
【测试分析】   
aarch64和x64都有问题，失败率2/100，复现命令：

```
function runJtreg() { jtreg -Xmixed -J-Djavatest.maxOutputSize=999999999  -timeoutFactor:4 -v:fail,error,time -nr -w $dir/index-$1 $test &> $dir/$1.log ; if [[ 0 -ne $? ]] ; then echo -n "$1 " ;else rm -rf $dir/index-$1 $dir/$1.log;fi ; } ; export -f runJtreg ; export dir="tmp-jtreg-"`basename ${test##* } .java | sed "s|#|_|"` ; rm -rf $dir ; mkdir -p $dir ; time seq 100 | xargs -i -n 1 -P 24 bash -c "runJtreg {}" ; echo total fail number: `ls $dir/*.log 2> /dev/null | wc | awk '{print $1}'`
21 4
real    1m0.785s
user    28m42.137s
sys     1m23.557s
total fail number: 2
```
【对比测试】

```
dragonwell17 release同样问题   
oss://dragonwell/17.0.13.0.14+9/Alibaba_Dragonwell_Standard_17.0.13.0.14.9_x64_linux.tar.gz   

 Temurin17 未复现    
oss://compiler-ci-bucket/openjdk/jdk-17.0.9-ga/OpenJDK17U-jdk_x64_linux_hotspot_17.0.9_9.tar.gz
```

【用例日志】

```
STDERR:
java.lang.OutOfMemoryError: GC overhead limit exceeded
	at jdk.jfr/jdk.jfr.internal.consumer.EventParser.parse(EventParser.java:150)
	at jdk.jfr/jdk.jfr.internal.consumer.ChunkParser.readEvent(ChunkParser.java:248)
	at jdk.jfr/jdk.jfr.consumer.RecordingFile.findNext(RecordingFile.java:261)
	at jdk.jfr/jdk.jfr.consumer.RecordingFile.<init>(RecordingFile.java:87)
	at jdk.jfr/jdk.jfr.consumer.RecordingFile.readAllEvents(RecordingFile.java:230)
	at jdk.test.lib.jfr.Events.fromRecording(Events.java:277)
	at jdk.jfr.event.gc.stacktrace.AllocationStackTrace.allocAndCheck(AllocationStackTrace.java:386)
	at jdk.jfr.event.gc.stacktrace.AllocationStackTrace.testAllocEvent(AllocationStackTrace.java:343)
	at jdk.jfr.event.gc.stacktrace.AllocationStackTrace.testParallelMarkSweepAllocEvent(AllocationStackTrace.java:237)
	at jdk.jfr.event.gc.stacktrace.TestParallelMarkSweepAllocationPendingStackTrace.main(TestParallelMarkSweepAllocationPendingStackTrace.java:37)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
	at com.sun.javatest.regtest.agent.MainWrapper$MainTask.run(MainWrapper.java:138)
	at java.base/java.lang.Thread.run(Thread.java:840)

JavaTest Message: Test threw exception: java.lang.OutOfMemoryError: GC overhead limit exceeded
JavaTest Message: shutting down test

```
【jdk版本】

```
java -version;java -Xinternalversion
openjdk version "17.0.13" 2024-10-15
OpenJDK Runtime Environment (Alibaba Dragonwell Standard Edition)-17.0.7.0.7+7-GA (build 17.0.13+7)
OpenJDK 64-Bit Server VM (Alibaba Dragonwell Standard Edition)-17.0.7.0.7+7-GA (build 17.0.13+7, mixed mode, sharing)
OpenJDK 64-Bit Server VM (17.0.13+7) for linux-amd64 JRE (17.0.13+7), built on Oct 15 2024 00:00:00 by "dragonwell" with gcc 10.3.0
```
【系统版本信息】

```
uname -a ; cat /etc/os-release ; free -h ; lscpu | head -n 25
Linux CompilerTest-x64-3 5.10.134-16.1.al8.x86_64 #1 SMP Thu Dec 7 14:11:24 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
NAME="Alibaba Cloud Linux"
VERSION="3 (Soaring Falcon)"
ID="alinux"
ID_LIKE="rhel fedora centos anolis"
VERSION_ID="3"
UPDATE_ID="9"
PLATFORM_ID="platform:al8"
PRETTY_NAME="Alibaba Cloud Linux 3 (Soaring Falcon)"
ANSI_COLOR="0;31"
HOME_URL="https://www.aliyun.com/"

              total        used        free      shared  buff/cache   available
Mem:          123Gi       4.6Gi       114Gi       3.0Mi       4.7Gi       117Gi
Swap:            0B          0B          0B
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              32
On-line CPU(s) list: 0-31
Thread(s) per core:  2
Core(s) per socket:  16
Socket(s):           1
NUMA node(s):        1
Vendor ID:           GenuineIntel
CPU family:          6
Model:               106
Model name:          Intel(R) Xeon(R) Platinum 8369B CPU @ 2.70GHz
Stepping:            6
CPU MHz:             3498.033
BogoMIPS:            5399.99
Hypervisor vendor:   KVM
Virtualization type: full
L1d cache:           48K
L1i cache:           32K
L2 cache:            1280K
L3 cache:            49152K
NUMA node0 CPU(s):   0-31
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq monitor ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch cpuid_fault invpcid_single ibrs_enhanced fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves wbnoinvd arat avx512vbmi pku ospke avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg avx512_vpopcntdq rdpid fsrm arch_capabilities

```

**Comment by sendaoYan** [comment]
https://github.com/openjdk/jdk17u-dev/pull/3109
