### ISSUE TITLE
【上游问题】-Xcomp选项运行用例java/rmi/server/RMISocketFactory/useSocketFactory/unicast/UseCustomSocketFactory.java随机报错

### ISSUE THREAD

**Issue by sendaoYan** [alibaba/dragonwell17#45]
https://tone.aliyun-inc.com/ws/xesljfzh/test_result/147439?tab=1

```log
STDOUT:

Regression test for bug 4127826

EchoServer: creating remote object
EchoServer: binding in registry
STDERR:
WARNING: A command line option has enabled the Security Manager
WARNING: The Security Manager is deprecated and will be removed in a future release
test policy: =/tmp/tone/run/jtreg/jt-work/test_jdk/java/rmi/server/RMISocketFactory/useSocketFactory/unicast/UseCustomSocketFactory/security.policy_new

using protocol: none
JAVAVM: command = [/opt/java/openjdk/bin/java, -Xcomp, -ea, -esa, -Djava.security.manager=allow, -Djava.security.policy==/tmp/tone/run/jtreg/jt-work/test_jdk/java/rmi/server/RMISocketFactory/useSocketFactory/unicast/UseCustomSocketFactory/security.policy_new, -Drmi.registry.port=33109, EchoImpl]
WARNING: A terminally deprecated method in java.lang.System has been called
WARNING: System::setSecurityManager has been called by TestLibrary (file:/tmp/tone/run/jtreg/jt-work/test_jdk/classes/190/java/rmi/testlibrary/)
WARNING: Please consider reporting this to the maintainers of TestLibrary
WARNING: System::setSecurityManager will be removed in a future release
TEST FAILED: server not bound in 8 tries
TEST FAILED: 
Test failed with: EchoServer
java.rmi.NotBoundException: EchoServer
	at java.rmi/sun.rmi.registry.RegistryImpl.unbind(RegistryImpl.java:273)
	at java.rmi/sun.rmi.registry.RegistryImpl_Skel.dispatch(RegistryImpl_Skel.java:186)
	at java.rmi/sun.rmi.server.UnicastServerRef.oldDispatch(UnicastServerRef.java:470)
	at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:299)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:200)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:712)
	at java.rmi/sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:587)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:828)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:705)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:704)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
	at java.rmi/sun.rmi.transport.StreamRemoteCall.exceptionReceivedFromServer(StreamRemoteCall.java:304)
	at java.rmi/sun.rmi.transport.StreamRemoteCall.executeCall(StreamRemoteCall.java:280)
	at java.rmi/sun.rmi.server.UnicastRef.invoke(UnicastRef.java:381)
	at java.rmi/sun.rmi.registry.RegistryImpl_Stub.unbind(RegistryImpl_Stub.java:180)
	at java.rmi/java.rmi.Naming.unbind(Naming.java:152)
	at UseCustomSocketFactory.main(UseCustomSocketFactory.java:112)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
	at java.base/java.lang.Thread.run(Thread.java:833)
TestFailedException: TEST FAILED: ; nested exception is: 
	java.rmi.NotBoundException: EchoServer
java.rmi.NotBoundException: EchoServer
	at java.rmi/sun.rmi.registry.RegistryImpl.unbind(RegistryImpl.java:273)
	at java.rmi/sun.rmi.registry.RegistryImpl_Skel.dispatch(RegistryImpl_Skel.java:186)
	at java.rmi/sun.rmi.server.UnicastServerRef.oldDispatch(UnicastServerRef.java:470)
	at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:299)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:200)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:712)
	at java.rmi/sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:587)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:828)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:705)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:704)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
	at java.rmi/sun.rmi.transport.StreamRemoteCall.exceptionReceivedFromServer(StreamRemoteCall.java:304)
	at java.rmi/sun.rmi.transport.StreamRemoteCall.executeCall(StreamRemoteCall.java:280)
	at java.rmi/sun.rmi.server.UnicastRef.invoke(UnicastRef.java:381)
	at java.rmi/sun.rmi.registry.RegistryImpl_Stub.unbind(RegistryImpl_Stub.java:180)
	at java.rmi/java.rmi.Naming.unbind(Naming.java:152)
	at UseCustomSocketFactory.main(UseCustomSocketFactory.java:112)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
	at java.base/java.lang.Thread.run(Thread.java:833)

JavaTest Message: Test threw exception: TestFailedException: TEST FAILED: ; nested exception is: 
	java.rmi.NotBoundException: EchoServer
JavaTest Message: shutting down test

STATUS:Failed.`main' threw exception: TestFailedException: TEST FAILED: ; nested exception is: java.rmi.NotBoundException: EchoServer
rerun:
cd /tmp/tone/run/jtreg/jt-work/test_jdk/java/rmi/server/RMISocketFactory/useSocketFactory/unicast/UseCustomSocketFactory && \
DISPLAY=:7 \
HOME=/root \
LANG=en_US.UTF-8 \
PATH=/bin:/usr/bin:/usr/sbin \
TEST_IMAGE_DIR=/tmp/tone/run/jtreg/test-images \
CLASSPATH=/tmp/tone/run/jtreg/jt-work/test_jdk/classes/190/java/rmi/server/RMISocketFactory/useSocketFactory/unicast/UseCustomSocketFactory.d:/tmp/tone/run/jtreg/jdk-repo/test/jdk/java/rmi/server/RMISocketFactory/useSocketFactory/unicast:/tmp/tone/run/jtreg/jt-work/test_jdk/classes/190/java/rmi/testlibrary:/tmp/tone/run/jtreg/jdk-repo/test/jdk/java/rmi/testlibrary:/tmp/tone/run/jtreg/jtreg/lib/javatest.jar:/tmp/tone/run/jtreg/jtreg/lib/jtreg.jar \
    /opt/java/openjdk/bin/java \
        -Dtest.vm.opts='-Xcomp -ea -esa' \
        -Dtest.tool.vm.opts='-J-Xcomp -J-ea -J-esa' \
        -Dtest.compiler.opts= \
        -Dtest.java.opts= \
        -Dtest.jdk=/opt/java/openjdk \
        -Dcompile.jdk=/opt/java/openjdk \
        -Dtest.timeout.factor=4.0 \
        -Dtest.nativepath=/tmp/tone/run/jtreg/test-images/hotspot/jtreg/native \
        -Dtest.root=/tmp/tone/run/jtreg/jdk-repo/test/jdk \
        -Dtest.name=java/rmi/server/RMISocketFactory/useSocketFactory/unicast/UseCustomSocketFactory.java \
        -Dtest.file=/tmp/tone/run/jtreg/jdk-repo/test/jdk/java/rmi/server/RMISocketFactory/useSocketFactory/unicast/UseCustomSocketFactory.java \
        -Dtest.src=/tmp/tone/run/jtreg/jdk-repo/test/jdk/java/rmi/server/RMISocketFactory/useSocketFactory/unicast \
        -Dtest.src.path=/tmp/tone/run/jtreg/jdk-repo/test/jdk/java/rmi/server/RMISocketFactory/useSocketFactory/unicast:/tmp/tone/run/jtreg/jdk-repo/test/jdk/java/rmi/testlibrary \
        -Dtest.classes=/tmp/tone/run/jtreg/jt-work/test_jdk/classes/190/java/rmi/server/RMISocketFactory/useSocketFactory/unicast/UseCustomSocketFactory.d \
        -Dtest.class.path=/tmp/tone/run/jtreg/jt-work/test_jdk/classes/190/java/rmi/server/RMISocketFactory/useSocketFactory/unicast/UseCustomSocketFactory.d:/tmp/tone/run/jtreg/jt-work/test_jdk/classes/190/java/rmi/testlibrary \
        -Dtest.modules='java.rmi/sun.rmi.registry java.rmi/sun.rmi.server java.rmi/sun.rmi.transport java.rmi/sun.rmi.transport.tcp' \
        -Djava.security.policy==/tmp/tone/run/jtreg/jt-work/test_jdk/java/rmi/server/RMISocketFactory/useSocketFactory/unicast/UseCustomSocketFactory/security.policy_new \
        -Djava.security.manager=default \
        --add-modules java.rmi \
        --add-exports java.rmi/sun.rmi.registry=ALL-UNNAMED \
        --add-exports java.rmi/sun.rmi.server=ALL-UNNAMED \
        --add-exports java.rmi/sun.rmi.transport=ALL-UNNAMED \
        --add-exports java.rmi/sun.rmi.transport.tcp=ALL-UNNAMED \
        -Xcomp \
        -ea \
        -esa \
        -Djava.library.path=/tmp/tone/run/jtreg/test-images/hotspot/jtreg/native \
        com.sun.javatest.regtest.agent.MainWrapper /tmp/tone/run/jtreg/jt-work/test_jdk/java/rmi/server/RMISocketFactory/useSocketFactory/unicast/UseCustomSocketFactory.d/main.3.jta

TEST RESULT: Failed. Execution failed: `main' threw exception: TestFailedException: TEST FAILED: ; nested exception is: java.rmi.NotBoundException: EchoServer
```

replay command:
```bash
test=test/jdk/java/rmi/server/RMISocketFactory/useSocketFactory/unicast/UseCustomSocketFactory.java
nproc=`nproc` ; dir="tmp-jtreg-"`basename $test .java` ; rm -rf $dir ; mkdir -p $dir ; time seq 50 | xargs -i -n 1 -P $nproc bash -c "jtreg -Xcomp -ea -esa -timeoutFactor:2 -v:fail,error,time,nopass -nr -w $dir/index-{} $test &> $dir/{}.log ; grep 'Test results: passed: 1' -L $dir/{}.log"
```
复现概率：48/50

[9.log](https://github.com/alibaba/dragonwell17/files/10789100/9.log)
[8.log](https://github.com/alibaba/dragonwell17/files/10789101/8.log)
[7.log](https://github.com/alibaba/dragonwell17/files/10789102/7.log)
[6.log](https://github.com/alibaba/dragonwell17/files/10789103/6.log)
[5.log](https://github.com/alibaba/dragonwell17/files/10789104/5.log)
[4.log](https://github.com/alibaba/dragonwell17/files/10789105/4.log)
[48.log](https://github.com/alibaba/dragonwell17/files/10789106/48.log)

**Comment by sendaoYan** [comment]
java/rmi/server/Unreferenced/leaseCheckInterval/LeaseCheckInterval.java

```
STDERR:

Regression test for bug 4285878

exported remote object
created local registry
bound remote object in local registry
starting remote client VM...
JAVAVM: command = [/opt/java/openjdk/bin/java, -Xcomp, -ea, -esa, -Drmi.registry.port=39085, SelfTerminator]
waiting for unreferenced() callback...
java.lang.RuntimeException: TEST FAILED: unreferenced() not invoked after 20.0 seconds
	at LeaseCheckInterval.main(LeaseCheckInterval.java:111)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
	at java.base/java.lang.Thread.run(Thread.java:833)

JavaTest Message: Test threw exception: java.lang.RuntimeException: TEST FAILED: unreferenced() not invoked after 20.0 seconds
JavaTest Message: shutting down test

STATUS:Failed.`main' threw exception: java.lang.RuntimeException: TEST FAILED: unreferenced() not invoked after 20.0 seconds
rerun:
cd /tmp/tone/run/jtreg/jt-work/test_jdk/java/rmi/server/Unreferenced/leaseCheckInterval/LeaseCheckInterval && \
DISPLAY=:7 \
HOME=/root \
LANG=en_US.UTF-8 \
PATH=/bin:/usr/bin:/usr/sbin \
TEST_IMAGE_DIR=/tmp/tone/run/jtreg/test-images \
CLASSPATH=/tmp/tone/run/jtreg/jt-work/test_jdk/classes/191/java/rmi/server/Unreferenced/leaseCheckInterval/LeaseCheckInterval.d:/tmp/tone/run/jtreg/jdk-repo/test/jdk/java/rmi/server/Unreferenced/leaseCheckInterval:/tmp/tone/run/jtreg/jt-work/test_jdk/classes/191/java/rmi/testlibrary:/tmp/tone/run/jtreg/jdk-repo/test/jdk/java/rmi/testlibrary:/tmp/tone/run/jtreg/jtreg/lib/javatest.jar:/tmp/tone/run/jtreg/jtreg/lib/jtreg.jar \
    /opt/java/openjdk/bin/java \
        -Dtest.vm.opts='-Xcomp -ea -esa' \
        -Dtest.tool.vm.opts='-J-Xcomp -J-ea -J-esa' \
        -Dtest.compiler.opts= \
        -Dtest.java.opts= \
        -Dtest.jdk=/opt/java/openjdk \
        -Dcompile.jdk=/opt/java/openjdk \
        -Dtest.timeout.factor=4.0 \
        -Dtest.nativepath=/tmp/tone/run/jtreg/test-images/hotspot/jtreg/native \
        -Dtest.root=/tmp/tone/run/jtreg/jdk-repo/test/jdk \
        -Dtest.name=java/rmi/server/Unreferenced/leaseCheckInterval/LeaseCheckInterval.java \
        -Dtest.file=/tmp/tone/run/jtreg/jdk-repo/test/jdk/java/rmi/server/Unreferenced/leaseCheckInterval/LeaseCheckInterval.java \
        -Dtest.src=/tmp/tone/run/jtreg/jdk-repo/test/jdk/java/rmi/server/Unreferenced/leaseCheckInterval \
        -Dtest.src.path=/tmp/tone/run/jtreg/jdk-repo/test/jdk/java/rmi/server/Unreferenced/leaseCheckInterval:/tmp/tone/run/jtreg/jdk-repo/test/jdk/java/rmi/testlibrary \
        -Dtest.classes=/tmp/tone/run/jtreg/jt-work/test_jdk/classes/191/java/rmi/server/Unreferenced/leaseCheckInterval/LeaseCheckInterval.d \
        -Dtest.class.path=/tmp/tone/run/jtreg/jt-work/test_jdk/classes/191/java/rmi/server/Unreferenced/leaseCheckInterval/LeaseCheckInterval.d:/tmp/tone/run/jtreg/jt-work/test_jdk/classes/191/java/rmi/testlibrary \
        -Dtest.modules='java.rmi/sun.rmi.registry java.rmi/sun.rmi.server java.rmi/sun.rmi.transport java.rmi/sun.rmi.transport.tcp' \
        --add-modules java.rmi \
        --add-exports java.rmi/sun.rmi.registry=ALL-UNNAMED \
        --add-exports java.rmi/sun.rmi.server=ALL-UNNAMED \
        --add-exports java.rmi/sun.rmi.transport=ALL-UNNAMED \
        --add-exports java.rmi/sun.rmi.transport.tcp=ALL-UNNAMED \
        -Xcomp \
        -ea \
        -esa \
        -Djava.library.path=/tmp/tone/run/jtreg/test-images/hotspot/jtreg/native \
        com.sun.javatest.regtest.agent.MainWrapper /tmp/tone/run/jtreg/jt-work/test_jdk/java/rmi/server/Unreferenced/leaseCheckInterval/LeaseCheckInterval.d/main.2.jta
```
